package com.example.se302;

import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;

public class ConvertToJSON {

    static ArrayList<String> fileList = new ArrayList();
    private static int sameFileCounter = 0;


    public static void generateJsonFile(Syllabus syllabus) {  ///// FILL THE BLANK PARTS

        if (syllabus.getCode() != null) {
            if (!fileList.contains("syllabus" + syllabus.getCode() + ".json")) {

                String filePath = "syllabus_" + syllabus.getCode() + ".json";
                sameFileCounter++;
                fileList.add("syllabus_" + syllabus.getCode() + ".json");

                String jsonString = "{\n"

                        //     + "Changes Detail: "
                        //     + "\"Code of the Class\" : \" " + syllabus.getCode() + "\n"
                        //     + "\"Editor Name and Surname\" : \" " + syllabus.getCode() + "\n"  //add editor info with get
                        //     + "\"Reason for Changes\" : \" " + syllabus.getCode() + "\n" // get why change info
                        //     + "\"When was change made\" : \" " + syllabus.getCode() + "\n" //get date box
                        //     + "\"What time was change made\" : \" " + syllabus.getCode() + "\n" //get time box
                        //     + "\"Language of the Syllabus\" : \" " + syllabus.getCode() + "\n" //get language

                        + "  \"courseName\": \"" + syllabus.getCourseName() + "\",\n"
                        + "  \"code\": \"" + syllabus.getCode() + "\",\n"
                        + "  \"fall\": \"" + syllabus.getFall() + "\",\n"
                        + "  \"spring\": \"" + syllabus.getSpring() + "\",\n"
                        + "  \"theory\": \"" + syllabus.getTheory() + "\",\n"
                        + "  \"localCredit\": \"" + syllabus.getLocalCredit() + "\",\n"
                        + "  \"ects\": \"" + syllabus.getEcts() + "\",\n"
                        + "  \"prerequisites\": \"" + syllabus.getPrerequisites() + "\",\n"
                        + "  \"lab\": \"" + syllabus.getLab() + "\",\n"
                        + "  \"courseLanguage\": \"" + syllabus.getCourseLanguage() + "\",\n"
                        + "  \"courseType\": \"" + syllabus.getCourseType() + "\",\n"
                        + "  \"courseLevel\": \"" + syllabus.getCourseLevel() + "\",\n"
                        + "  \"teachingMethods\": \"" + syllabus.getTeachingMethods() + "\",\n"
                        + "  \"courseCoordinator\": \"" + syllabus.getCourseCoordinator() + "\",\n"
                        + "  \"courseCoordinator2\": \"" + syllabus.getCourseCoordinator2() + "\",\n"
                        + "  \"assistant\": \"" + syllabus.getAssistant() + "\",\n"
                        + "  \"courseObjectives\": \"" + syllabus.getCourseObjectives() + "\",\n"
                        + "  \"learningOutcomes\": \"" + syllabus.getLearningOutcomes() + "\",\n"
                        + "  \"courseDescription\": \"" + syllabus.getCourseDescription() + "\",\n"
                        + "  \"Subjects Two\": \"" + syllabus.getSubjectsTwo() + "\",\n"
                        + "  \"Subjects Three\": \"" + syllabus.getSubjectsThree() + "\",\n"
                        + "  \"Subjects Four\": \"" + syllabus.getSubjectsFour() + "\",\n"
                        + "  \"Subjects Five\": \"" + syllabus.getSubjectsFive() + "\",\n"
                        + "  \"Subjects Six\": \"" + syllabus.getSubjectsSix() + "\",\n"
                        + "  \"Subjects Seven\": \"" + syllabus.getSubjectsSeven() + "\",\n"
                        + "  \"Subjects Eight\": \"" + syllabus.getSubjectsEight() + "\",\n"
                        + "  \"Subjects Nine\": \"" + syllabus.getSubjectsNine() + "\",\n"
                        + "  \"Subjects Ten\": \"" + syllabus.getSubjectsTen() + "\",\n"
                        + "  \"Subjects Eleven\": \"" + syllabus.getSubjectsEleven() + "\",\n"
                        + "  \"Subjects Twelve\": \"" + syllabus.getSubjectsTwelve() + "\",\n"
                        + "  \"Subjects Thirteen\": \"" + syllabus.getSubjectsThirteen() + "\",\n"
                        + "  \"Subjects Fourteen\": \"" + syllabus.getSubjectsFourteen() + "\",\n"
                        + "  \"Subjects Fifteen\": \"" + syllabus.getSubjectsFifteen() + "\",\n"
                        + "  \"Subjects Sixteen\": \"" + syllabus.getSubjectsSixteen() + "\",\n"
                        + "  \"Required Two\": \"" + syllabus.getRequiredMaterialsTwo() + "\",\n"
                        + "  \"Required Three\": \"" + syllabus.getRequiredMaterialsThree() + "\",\n"
                        + "  \"Required Four\": \"" + syllabus.getRequiredMaterialsFour() + "\",\n"
                        + "  \"Required Five\": \"" + syllabus.getRequiredMaterialsFive() + "\",\n"
                        + "  \"Required Six\": \"" + syllabus.getRequiredMaterialsSix() + "\",\n"
                        + "  \"Required Seven\": \"" + syllabus.getRequiredMaterialsSeven() + "\",\n"
                        + "  \"Required Eight\": \"" + syllabus.getRequiredMaterialsEight() + "\",\n"
                        + "  \"Required Nine\": \"" + syllabus.getRequiredMaterialsNine() + "\",\n"
                        + "  \"Required Ten\": \"" + syllabus.getRequiredMaterialsTen() + "\",\n"
                        + "  \"Required Eleven\": \"" + syllabus.getRequiredMaterialsEleven() + "\",\n"
                        + "  \"Required Twelve\": \"" + syllabus.getRequiredMaterialsTwelve() + "\",\n"
                        + "  \"Required Thirteen\": \"" + syllabus.getRequiredMaterialsThirteen() + "\",\n"
                        + "  \"Required Fourteen\": \"" + syllabus.getRequiredMaterialsFourteen() + "\",\n"
                        + "  \"Required Fifteen\": \"" + syllabus.getRequiredMaterialsFifteen() + "\",\n"
                        + "  \"Participation One\": \"" + syllabus.getParticipationOne() + "\",\n"
                        + "  \"Participation Two\": \"" + syllabus.getParticipationTwo() + "\",\n"
                        + "  \"Participation Three\": \"" + syllabus.getParticipationThree() + "\",\n"
                        + "  \"Participation Four\": \"" + syllabus.getParticipationFour() + "\",\n"
                        + "  \"Participation Five\": \"" + syllabus.getParticipationFive() + "\",\n"
                        + "  \"Participation Six\": \"" + syllabus.getParticipationSix() + "\",\n"
                        + "  \"Participation Seven\": \"" + syllabus.getParticipationSeven() + "\",\n"
                        + "  \"Participation Eight\": \"" + syllabus.getParticipationEight() + "\",\n"
                        + "  \"Participation Nine\": \"" + syllabus.getParticipationNine() + "\",\n"
                        + "  \"Laboratory One\": \"" + syllabus.getLaboratoryOne() + "\",\n"
                        + "  \"Laboratory Two\": \"" + syllabus.getLaboratoryTwo() + "\",\n"
                        + "  \"Laboratory Three\": \"" + syllabus.getLaboratoryThree() + "\",\n"
                        + "  \"Laboratory Four\": \"" + syllabus.getLaboratoryFour() + "\",\n"
                        + "  \"Laboratory Five\": \"" + syllabus.getLaboratoryFive() + "\",\n"
                        + "  \"Laboratory Six\": \"" + syllabus.getLaboratorySix() + "\",\n"
                        + "  \"Laboratory Seven\": \"" + syllabus.getLaboratorySeven() + "\",\n"
                        + "  \"Laboratory Eight\": \"" + syllabus.getLaboratoryEight() + "\",\n"
                        + "  \"Laboratory Nine\": \"" + syllabus.getLaboratoryNine() + "\",\n"
                        + "  \"FieldWork One\": \"" + syllabus.getFieldWorkOne() + "\",\n"
                        + "  \"FieldWork Two\": \"" + syllabus.getFieldWorkTwo() + "\",\n"
                        + "  \"FieldWork Three\": \"" + syllabus.getFieldWorkThree() + "\",\n"
                        + "  \"FieldWork Four\": \"" + syllabus.getFieldWorkFour() + "\",\n"
                        + "  \"FieldWork Five\": \"" + syllabus.getFieldWorkFive() + "\",\n"
                        + "  \"FieldWork Six\": \"" + syllabus.getFieldWorkSix() + "\",\n"
                        + "  \"FieldWork Seven\": \"" + syllabus.getFieldWorkSeven() + "\",\n"
                        + "  \"FieldWork Eight\": \"" + syllabus.getFieldWorkEight() + "\",\n"
                        + "  \"FieldWork Nine\": \"" + syllabus.getFieldWorkNine() + "\",\n"
                        + "  \"Quiz2 One\": \"" + syllabus.getQuiz2One() + "\",\n"
                        + "  \"Quiz2 Two\": \"" + syllabus.getQuiz2Two() + "\",\n"
                        + "  \"Quiz2 Three\": \"" + syllabus.getQuiz2Three() + "\",\n"
                        + "  \"Quiz Four\": \"" + syllabus.getQuizFour() + "\",\n"
                        + "  \"Quiz Five\": \"" + syllabus.getQuizFive() + "\",\n"
                        + "  \"Quiz Six\": \"" + syllabus.getQuizSix() + "\",\n"
                        + "  \"Quiz Seven\": \"" + syllabus.getQuizSeven() + "\",\n"
                        + "  \"Quiz Eight\": \"" + syllabus.getQuizEight() + "\",\n"
                        + "  \"Quiz Nine\": \"" + syllabus.getQuizNine() + "\",\n"
                        + "  \"Coursehour One\": \"" + syllabus.getCourseHourOne() + "\",\n"
                        + "  \"Coursehour Two\": \"" + syllabus.getCourseHourTwo() + "\",\n"
                        + "  \"Labhour One\": \"" + syllabus.getLabhourOne() + "\",\n"
                        + "  \"Labhour Two\": \"" + syllabus.getLabhourTwo() + "\",\n"
                        + "  \"Studyhour One\": \"" + syllabus.getStudyhourOne() + "\",\n"
                        + "  \"Studyhour Two\": \"" + syllabus.getStudyhourTwo() + "\",\n"
                        + "  \"Studyhour Three\": \"" + syllabus.getStudyhourThree() + "\",\n"
                        + "  \"Fieldwork One\": \"" + syllabus.getFieldworkOne() + "\",\n"
                        + "  \"Fieldwork Two\": \"" + syllabus.getFieldworkTwo() + "\",\n"
                        + "  \"Fieldwork Three\": \"" + syllabus.getFieldworkThree() + "\",\n"
                        + "  \"Quiz One\": \"" + syllabus.getQuizOne() + "\",\n"
                        + "  \"Quiz Two\": \"" + syllabus.getQuizTwo() + "\",\n"
                        + "  \"Quiz Three\": \"" + syllabus.getQuizThree() + "\",\n"
                        + "  \"Homework One\": \"" + syllabus.getHomeworkOne() + "\",\n"
                        + "  \"Homework Two\": \"" + syllabus.getHomeworkTwo() + "\",\n"
                        + "  \"Homework Three\": \"" + syllabus.getHomeworkThree() + "\",\n"
                        + "  \"Presentation One\": \"" + syllabus.getPresentationOne() + "\",\n"
                        + "  \"Presentation Two\": \"" + syllabus.getPresentationTwo() + "\",\n"
                        + "  \"Presentation Three\": \"" + syllabus.getPresentationThree() + "\",\n"
                        + "  \"Project One\": \"" + syllabus.getProjectOne() + "\",\n"
                        + "  \"Project Two\": \"" + syllabus.getProjectTwo() + "\",\n"
                        + "  \"Project Three\": \"" + syllabus.getProjectThree() + "\",\n"
                        + "  \"Portfolio One\": \"" + syllabus.getPortfolioOne() + "\",\n"
                        + "  \"Portfolio Two\": \"" + syllabus.getPortfolioTwo() + "\",\n"
                        + "  \"Portfolio Three\": \"" + syllabus.getPortfolioThree() + "\",\n"
                        + "  \"Seminar One\": \"" + syllabus.getSeminarOne() + "\",\n"
                        + "  \"Seminar Two\": \"" + syllabus.getSeminarTwo() + "\",\n"
                        + "  \"Seminar Three\": \"" + syllabus.getSeminarThree() + "\",\n"
                        + "  \"Oral One\": \"" + syllabus.getOralOne() + "\",\n"
                        + "  \"Oral Two\": \"" + syllabus.getOralTwo() + "\",\n"
                        + "  \"Oral Three\": \"" + syllabus.getOralThree() + "\",\n"
                        + "  \"Midterm One\": \"" + syllabus.getMidtermOne() + "\",\n"
                        + "  \"Midterm Two\": \"" + syllabus.getMidtermTwo() + "\",\n"
                        + "  \"Midterm Three\": \"" + syllabus.getMidtermThree() + "\",\n"
                        + "  \"Final One\": \"" + syllabus.getFinalOne() + "\",\n"
                        + "  \"Final Two\": \"" + syllabus.getFinalTwo() + "\",\n"
                        + "  \"Final Three\": \"" + syllabus.getFinalThree() + "\",\n"
                        + "  \"OneProgram Zero\": \"" + syllabus.getOneProgramZero() + "\",\n"
                        + "  \"OneProgram One\": \"" + syllabus.getOneProgramOne() + "\",\n"
                        + "  \"OneProgram Two\": \"" + syllabus.getOneProgramTwo() + "\",\n"
                        + "  \"OneProgram Three\": \"" + syllabus.getOneProgramThree() + "\",\n"
                        + "  \"OneProgram Four\": \"" + syllabus.getOneProgramFour() + "\",\n"
                        + "  \"OneProgram Five\": \"" + syllabus.getOneProgramFive() + "\",\n"
                        + "  \"TwoProgramZero\": \"" + syllabus.getTwoProgramZero() + "\",\n"
                        + "  \"TwoProgramOne\": \"" + syllabus.getTwoProgramOne() + "\",\n"
                        + "  \"TwoProgramTwo\": \"" + syllabus.getTwoProgramTwo() + "\",\n"
                        + "  \"TwoProgramThree\": \"" + syllabus.getTwoProgramThree() + "\",\n"
                        + "  \"TwoProgramFour\": \"" + syllabus.getTwoProgramFour() + "\",\n"
                        + "  \"TwoProgramFive\": \"" + syllabus.getTwoProgramFive() + "\",\n"
                        + "  \"ThreeProgramZero\": \"" + syllabus.getThreeProgramZero() + "\",\n"
                        + "  \"ThreeProgramOne\": \"" + syllabus.getThreeProgramOne() + "\",\n"
                        + "  \"ThreeProgramTwo\": \"" + syllabus.getThreeProgramTwo() + "\",\n"
                        + "  \"ThreeProgramThree\": \"" + syllabus.getThreeProgramThree() + "\",\n"
                        + "  \"ThreeProgramFour\": \"" + syllabus.getThreeProgramFour() + "\",\n"
                        + "  \"ThreeProgramFive\": \"" + syllabus.getThreeProgramFive() + "\",\n"
                        + "  \"FourProgramZero\": \"" + syllabus.getFourProgramZero() + "\",\n"
                        + "  \"FourProgramOne\": \"" + syllabus.getFourProgramOne() + "\",\n"
                        + "  \"FourProgramTwo\": \"" + syllabus.getFourProgramTwo() + "\",\n"
                        + "  \"FourProgramThree\": \"" + syllabus.getFourProgramThree() + "\",\n"
                        + "  \"FourProgramFour\": \"" + syllabus.getFourProgramFour() + "\",\n"
                        + "  \"FourProgramFive\": \"" + syllabus.getFourProgramFive() + "\",\n"
                        + "  \"FiveProgramZero\": \"" + syllabus.getFiveProgramZero() + "\",\n"
                        + "  \"FiveProgramOne\": \"" + syllabus.getFiveProgramOne() + "\",\n"
                        + "  \"FiveProgramTwo\": \"" + syllabus.getFiveProgramTwo() + "\",\n"
                        + "  \"FiveProgramThree\": \"" + syllabus.getFiveProgramThree() + "\",\n"
                        + "  \"FiveProgramFour\": \"" + syllabus.getFiveProgramFour() + "\",\n"
                        + "  \"FiveProgramFive\": \"" + syllabus.getFiveProgramFive() + "\",\n"
                        + "  \"SixProgramZero\": \"" + syllabus.getSixProgramZero() + "\",\n"
                        + "  \"SixProgramOne\": \"" + syllabus.getSixProgramOne() + "\",\n"
                        + "  \"SixProgramTwo\": \"" + syllabus.getSixProgramTwo() + "\",\n"
                        + "  \"SixProgramThree\": \"" + syllabus.getSixProgramThree() + "\",\n"
                        + "  \"SixProgramFour\": \"" + syllabus.getSixProgramFour() + "\",\n"
                        + "  \"SixProgramFive\": \"" + syllabus.getSixProgramFive() + "\",\n"
                        + "  \"SevenProgramZero\": \"" + syllabus.getSevenProgramZero() + "\",\n"
                        + "  \"SevenProgramOne\": \"" + syllabus.getSevenProgramOne() + "\",\n"
                        + "  \"SevenProgramTwo\": \"" + syllabus.getSevenProgramTwo() + "\",\n"
                        + "  \"SevenProgramThree\": \"" + syllabus.getSevenProgramThree() + "\",\n"
                        + "  \"SevenProgramFour\": \"" + syllabus.getSevenProgramFour() + "\",\n"
                        + "  \"SevenProgramFive\": \"" + syllabus.getSevenProgramFive() + "\",\n"
                        + "  \"EightProgramZero\": \"" + syllabus.getEightProgramZero() + "\",\n"
                        + "  \"EightProgramOne\": \"" + syllabus.getEightProgramOne() + "\",\n"
                        + "  \"EightProgramTwo\": \"" + syllabus.getEightProgramTwo() + "\",\n"
                        + "  \"EightProgramThree\": \"" + syllabus.getEightProgramThree() + "\",\n"
                        + "  \"EightProgramFour\": \"" + syllabus.getEightProgramFour() + "\",\n"
                        + "  \"EightProgramFive\": \"" + syllabus.getEightProgramFive() + "\",\n"
                        + "  \"NineProgramZero\": \"" + syllabus.getNineProgramZero() + "\",\n"
                        + "  \"NineProgramOne\": \"" + syllabus.getNineProgramOne() + "\",\n"
                        + "  \"NineProgramTwo\": \"" + syllabus.getNineProgramTwo() + "\",\n"
                        + "  \"NineProgramThree\": \"" + syllabus.getNineProgramThree() + "\",\n"
                        + "  \"NineProgramFour\": \"" + syllabus.getNineProgramFour() + "\",\n"
                        + "  \"NineProgramFive\": \"" + syllabus.getNineProgramFive() + "\",\n"
                        + "  \"TenProgramZero\": \"" + syllabus.getTenProgramZero() + "\",\n"
                        + "  \"TenProgramOne\": \"" + syllabus.getTenProgramOne() + "\",\n"
                        + "  \"TenProgramTwo\": \"" + syllabus.getTenProgramTwo() + "\",\n"
                        + "  \"TenProgramThree\": \"" + syllabus.getTenProgramThree() + "\",\n"
                        + "  \"TenProgramFour\": \"" + syllabus.getTenProgramFour() + "\",\n"
                        + "  \"TenProgramFive\": \"" + syllabus.getTenProgramFive() + "\",\n"
                        + "  \"ElevenProgramZero\": \"" + syllabus.getElevenProgramZero() + "\",\n"
                        + "  \"ElevenProgramOne\": \"" + syllabus.getElevenProgramOne() + "\",\n"
                        + "  \"ElevenProgramTwo\": \"" + syllabus.getElevenProgramTwo() + "\",\n"
                        + "  \"ElevenProgramThree\": \"" + syllabus.getElevenProgramThree() + "\",\n"
                        + "  \"ElevenProgramFour\": \"" + syllabus.getElevenProgramFour() + "\",\n"
                        + "  \"ElevenProgramFive\": \"" + syllabus.getElevenProgramFive() + "\",\n"
                        + "  \"TwelveProgramZero\": \"" + syllabus.getTwelveProgramZero() + "\",\n"
                        + "  \"TwelveProgramOne\": \"" + syllabus.getTwelveProgramOne() + "\",\n"
                        + "  \"TwelveProgramTwo\": \"" + syllabus.getTwelveProgramTwo() + "\",\n"
                        + "  \"TwelveProgramThree\": \"" + syllabus.getTwelveProgramThree() + "\",\n"
                        + "  \"TwelveProgramFour\": \"" + syllabus.getTwelveProgramFour() + "\",\n"
                        + "  \"TwelveProgramFive\": \"" + syllabus.getTwelveProgramFive() + "\",\n"
                        + "  \"ThirteenProgramZero\": \"" + syllabus.getThirteenProgramZero() + "\",\n"
                        + "  \"ThirteenProgramOne\": \"" + syllabus.getThirteenProgramOne() + "\",\n"
                        + "  \"ThirteenProgramTwo\": \"" + syllabus.getThirteenProgramTwo() + "\",\n"
                        + "  \"ThirteenProgramThree\": \"" + syllabus.getThirteenProgramThree() + "\",\n"
                        + "  \"ThirteenProgramFour\": \"" + syllabus.getThirteenProgramFour() + "\",\n"
                        + "  \"ThirteenProgramFive\": \"" + syllabus.getThirteenProgramFive() + "\",\n"
                        + "  \"teachingMethods\": \"" + syllabus.getTeachingMethods() + "\"\n"
                        + "}";

                // Write the JSON string to a file
                try (FileWriter fileWriter = new FileWriter(filePath)) {
                    fileWriter.write(jsonString);
                    System.out.println("Data written to " + filePath);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }  /* else if (fileList.contains("syllabus" + syllabus.getCode() + ".json"){
           String filePath = "syllabus_" + syllabus.getCode() + sameFileCounter + ".json";
        } */     //IF THERE IS A FILE WITH THE SAME NAME,
                 //ADD THE FILE NAME (1), (2) ,...
        else{
            System.out.println("Please enter the course code");
        }
    }

}
